### ISSUE TITLE
Error when setting enterAnimation and leaveAnimation props to false.

### ISSUE THREAD

**Issue by rubencodes** [joshwcomeau/react-flip-move#34] opened 2016-04-19 17:48 UTC
Hello,

First off, thank you for your work on this project! I absolutely love it to death. 

I wanted to disable the v2.0 enter/leave animations (*I* like it but my boss had reservations). When I set the props, to false, I received this error: 
```
FlipMove.js:438 Uncaught TypeError: Cannot read property 'left' of undefined
```

Worth noting that it still behaved properly and did disable the animation, but I did encounter this issue.

**Comment by joshwcomeau** [comment] 2016-04-20 13:06
Thanks for the kind words, and for letting me know about this issue!

Interesting. I'll take a look at that. I have a vague idea what could be causing it.

**Comment by emilecantin** [comment] 2016-04-20 17:32
If it can help... I'm currently debugging through this issue, and it looks like it comes from the fact that this line: 

```
      var oldBox = this.boundingBoxes[key];
```
returns `undefined`. I do have an item in `this.boundingBoxes` (and I have only one child item, so it should match, I think).

The `key` I get here is a weird string, though (`".$14611644139820"`), not the key I set on my element.

Would that be related?

**Comment by emilecantin** [comment] 2016-04-20 17:37
Looks like replacing the above line with the following solves the problem:

```
      var oldBox = this.boundingBoxes[key] || {left: 0, top: 0};
```
Want me to open a PR?

**Comment by joshwcomeau** [comment] 2016-04-20 20:08
So, that is definitely a fix, but it's addressing the symptom, not the cause.

`boundingBoxes` is an object that holds all "tracked" DOM positions, so that when it comes time to rearrange or remove them, it knows where they were _before_ the update. This bug sounds like I'm neglecting to add children to the `boundingBoxes` object.

I expect this to be a quick fix now that I see what the problem is. Thanks for your help :) I don't think a PR is necessary though. I'll try to get a fix released in the next 5-6 hours.

**Comment by joshwcomeau** [comment] 2016-04-21 01:59
Hmm, so I'm unable to reproduce the issue locally. I read through the code and I can't see any problems with it, either. 

To confirm, the message is shown when you pass the following props:

```js
<FlipMove enterAnimation={false} leaveAnimation={false}>
```

When does the error pop up? When items are shuffled, removed, or added? 

Can you share more info about the context the error happens in?

Thanks :)

**Comment by rubencodes** [comment] 2016-04-21 08:30
That is correct! The error for me happens always on first leave (and then doesn't happen again).

**Comment by emilecantin** [comment] 2016-04-21 18:43
I think my issue might be different... I get it on initial load, and it doesn't depend on the animation props, I get the error even with a simple declaration like that:
```
              <FlipMove
                className="moveWrapper"
                duration={100}
              >
```
My children items are pretty complex, however, and it doesn't happen when it's already rendered on the server. I also have another `<FlipMove>` deeper into the hierarchy. Also, the children are shown after a fetch from the server, so there's a delay before they're rendered, but the last child is always there.

Hope this helps! I'll try to reproduce the issue in a codepen when I get the chance.

**Comment by joshwcomeau** [comment] 2016-04-21 20:30
@emilecantin thanks for the additional info! 

If you can reproduce it in a codepen I would super super appreciate it. It's tough when you can't replicate an issue, because I know this is probably affecting a lot of people but I don't know how to fix it.

Also, I never answered your question about the `key`. I use React.Children.toArray`, which modifies the keys, but in my experience it just prefixes it with `.$`. So I see stuff like `.$list-item-a`.

@rubencodes is the error message bugging you? I can draft a beta release that implements Emile's bandaid solution while we hunt for the deeper problem :)

**Comment by joshwcomeau** [comment] 2016-04-28 12:20
Hi @emilecantin,

Sorry to bug you, but have you had the chance to create a codepen repro? Would love to get this fixed :)

Thanks!

**Comment by emilecantin** [comment] 2016-04-28 12:45
Not yet, I've been pretty busy lately...

**Comment by rubencodes** [comment] 2016-05-29 05:29
FYI this error has started causing more significant (i.e. breaking) problems in my app, so I applied the above `var oldBox = this.boundingBoxes[key] || {left: 0, top: 0};` solution and it looks like all systems are go. Hope this gets solved eventually!

**Comment by joshwcomeau** [comment] 2016-05-29 10:34
Yeah, I think until I have time to do a deep debug, the band-aid solution is alright. Will fix :)

**Comment by joshwcomeau** [comment] 2016-05-29 10:41
ok, band-aid fix released!

**Closed by joshwcomeau** 2016-05-29 10:41 UTC
Labels: bug
