### ISSUE TITLE
Component not removed from DOM

### ISSUE THREAD

**Issue by gildas-mgd** [joshwcomeau/react-flip-move#168] opened 2017-06-23 07:43 UTC
Hi. I made a small example to reproduce a bug I had : https://codepen.io/anon/pen/PjjONp
It works if you click "Open popup 1" and then "Open popup 2" slowly, but if you click quickly (while the first transition is not ended), then the Popup 2 remains visible even after you close it.
It's happening on Chrome and Edge only.

I guess it's related to #120, and the fade hack (here : https://github.com/joshwcomeau/react-flip-move/issues/120#issuecomment-278125404) is working...

**Comment by Hypnosphi** [comment] 2017-06-25 14:09
Yes, looks like quite the same issue

**Comment by joshwcomeau** [comment] 2017-06-28 11:36
Yeah, sorry about that! Closing because this is a duplicate of #120.

**Closed by joshwcomeau** 2017-06-28 11:36 UTC
