### ISSUE TITLE
Cannot read property 'top' of undefined / 'getBoundingClientRect' of null

### ISSUE THREAD

**Issue by ConneXNL** [joshwcomeau/react-flip-move#106] opened 2016-11-23 13:34 UTC
When removing adding and removing items the FlipMove breaks with the error:

Uncaught TypeError: Cannot read property 'top' of undefined:
https://github.com/joshwcomeau/react-flip-move/blob/master/src/dom-manipulation.js#L141

Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null:
And https://github.com/joshwcomeau/react-flip-move/blob/master/src/prop-converter.js#L217

You can see these errors being thrown by clicking rapidly on the add / remove buttons using the following example:
https://gist.github.com/ConneXNL/c320db6f8898982f78b1b5cd4dc4cfea

**Comment by joshwcomeau** [comment] 2016-11-23 14:54
Hm, strange.

Can you test this with `2.6.8`? I refactored how enter/leave animations were tackled, and possibly there's a regression.

(There is a visual bug in earlier versions where animations restart when added/removed in quick succession - I'm mostly just curious about console errors)

**Comment by Arinteck** [comment] 2016-11-25 11:07
I've reproduced it with v2.6.8. It's happens when items quickly adding/removing from list.

**Comment by vsaarinen** [comment] 2016-11-25 16:13
Same thing here on v2.6.8. https://github.com/joshwcomeau/react-flip-move/blob/master/src/prop-converter.js#L217 is throwing with

```
TypeError: Cannot read property 'getBoundingClientRect' of null
```

**Comment by joshwcomeau** [comment] 2016-11-25 16:17
@Arinteck @vsaarinen thanks for confirming. Afraid I don't have a great answer for you; interrupted leave animations have always been iffy. I was hoping the newer version removed a lot of the hurdles, but apparently not.

I think in the short-term your best bet is to speed up animations, or throttle item removal.

**Comment by vsaarinen** [comment] 2016-11-25 16:24
I'm going to have to do some testing in order to make sure that this is actually the case, but I'm pretty sure the error happens during enter animations. I get it as soon as I load our app.

**Comment by vsaarinen** [comment] 2016-11-25 16:33
If it's of any help, `getPosition` is called from here when it occurs: https://github.com/joshwcomeau/react-flip-move/blob/master/src/FlipMove.js#L396

**Comment by vsaarinen** [comment] 2016-11-25 17:28
After upgrading NPM packages one by one, the culprit ended up being another package's bug: https://github.com/danawoodman/react-fontawesome/issues/32

The latest version of react-flip-move works fine now. Sorry for the false alarm.

**Comment by joshwcomeau** [comment] 2016-11-25 20:26
Weird! Thanks for the heads-up @vsaarinen 

I think there's maybe still a bug with FlipMove, because I've seen a similar issue on a jsbin without this dependency. Likely this other package was exacerbating it though.

**Comment by migreva** [comment] 2016-11-29 17:19
We've been seeing this issue as well. I did a little version binary search and found that (at least for our use case) [2.6.6](https://github.com/joshwcomeau/react-flip-move/releases/tag/v2.6.6) introduced the error. [2.6.5](https://github.com/joshwcomeau/react-flip-move/releases/tag/v2.6.5) works fine in our testing, but 2.6.6 throws the errors above.

**Comment by joshwcomeau** [comment] 2016-11-29 17:37
@migreva interesting! Thanks for finding the bug's introduction patch.

This is good news; that change was small, so we know exactly where the problem is. Was worried the problem would have been very difficult to find.

If it's as easy to fix as it is to find, it should be fixed soon! I'm pretty busy with work this week but I'll try to find time to tackle this.

**Comment by vsaarinen** [comment] 2016-11-30 09:20
FYI, for us, the problem occurred with 2.6.2. It might have occurred with older versions as well, but that's how far back I tested this.

**Comment by RyanCCollins** [comment] 2016-11-30 14:58
I am also seeing this issue with the latest release and it seems to be breaking it pretty consistently.

Let me know if you need any more details. Thanks!

**Comment by benjiwheeler** [comment] 2016-12-01 05:15
I'm also getting this on 2.7.1. Thanks, really enjoying react-flip-move !

**Comment by finetype** [comment] 2016-12-02 20:21
Also getting this issue. I'm using 2.7.1. It can be found if you play with our site, thezebra.com, enough--after a few server requests, with things being added and removed from the list, eventually React loses track of some DOM nodes and you get nodes sitting on top of each other. The other library we're using to animate sliding then creates all kinds of weird artifacts.

**Comment by ohjames** [comment] 2016-12-03 14:45
I'm seeing it in 2.6.5 and 2.7.1

**Comment by ohjames** [comment] 2016-12-03 14:54
Updated my previous comment... 2.6.5 seems to be working fine for now, but 2.6.4 and 2.6.6 both show the error.

**Comment by joshwcomeau** [comment] 2016-12-03 14:55
Very strange. I'm going to spend an hour on this today, hopefully I can get to the bottom of it!

**Closed** 2016-12-04 21:53 UTC
Labels: bug

**Comment by joshwcomeau** [comment] 2016-12-04 22:12
Hey guys,

So, I spent some time on this and was unable to find a perfect solution :(

The best I could do in the time available was a band-aid; Essentially I didn't try to account for the displacement of elements whose bounding box wasn't calculated in time.

What it means is that you should no longer experience this error, nor should everything "freeze up". There's still an underlying issue, though, of items sometimes "jumping" to the wrong place when several "leave" animations are triggered in a row.

In my (admittedly contrived) testing, shuffle interruptions were fine, and you could be a little cavalier with interrupts without issue (it's fine if you have 500ms animation duration and interrupt it once per 500ms cycle, but not more than that).

My solution for the jumping issue would be to recommend that you "batch" exits, using a throttle or a debounce. I haven't tried it, but it should be pretty simple - if there are issues with that approach, please let me know :)

One final thing: This PR added sequencing support for the stories. I use React Storybook for experimenting during development, and now you can create stories that set up specific sequences. Eg:

```js
[
  { eventName: 'removeItem', delay: 200 },
  { eventName: 'shuffle', delay: 100 },
  { eventName: 'restoreItems', delay: 400 },
]
```

If anyone would like to contribute towards fixing this issue, there is now a really simple way to set up a good debugging environment :)

cc @ConneXNL @Arinteck @vsaarinen @ohjames @migreva @RyanCCollins @benjiwheeler @finetype

**Comment by finetype** [comment] 2016-12-13 02:04
Throttling additions/removals ends up being a little more complicated than it seems on the surface. I'd like to contribute a 'dirty patch' to fix the library using the technique here (this is a hotfix for our website, which uses large numbers of exits rapidly at times, so please forgive the questionable code quality), but for now, I just wanted to make this available to others who may have this issue:

```

throttleChanges(newRates) {
        // THROTTLING ANIMATIONS
        // because of a current bug in react-flip-move, we throttle animations so we don't overwhelm
        // the algo determining the movements of everything, as recommended by author:
        // https://github.com/joshwcomeau/react-flip-move/issues/106
        window.clearTimeout(window.currentTimeout);
        let output;
        let timer = this.state.timeout;

        const uninitialized = !this.state.hasOwnProperty('renderedRates')
        // initialization of new prop to handle throttling first time through.
        if (uninitialized) {
            timer = 2550;
            window.currentTimeout = setTimeout(() => this.setState({renderedRates: newRates, timeout: timer}), timer);
            output = newRates;
        }
        else {
            timer = this.state.timeout
            const currentOnScreenRates = this.state.renderedRates.slice(0)
            let willRenderRates;

            let updated = newRates.some((newRate, index) => {
                // In this loop, we look over the latest rates, and find the first difference
                // with the rendered rates--if/when found, we will update willRenderRates
                // with that one difference.
                const currentRate = this.state.renderedRates[index];

                if (index === currentOnScreenRates.length) {
                    // have passed end of currentOnScreenRates.
                    // nothing to remove or change, just add, then break loop.
                    // (because adding to end doesn't cause glitch, can add all at once to end.)
                    const remainingRates = newRates.slice(index, newRates.length);
                    willRenderRates = currentOnScreenRates.concat(remainingRates);
                    window.currentTimeout = setTimeout(() => this.setState({ renderedRates: willRenderRates, timeout: timer }), timer);                    
                    return this.breakLoop();
                }
                else if (newRate.key === currentRate.key) {
                    // no change, carry on looping
                    return this.continueLoop();
                }
                else {
                    // we found a mismatch, splice new one into place of mismatch and exit loop.
                    currentOnScreenRates.splice(index, 1, newRate);

                    // filter out older instances of that rate.
                    let newRateCount = 0;
                    willRenderRates = currentOnScreenRates.filter(onScreenRate => {
                        if (onScreenRate && newRate.key === onScreenRate.key) {
                            newRateCount++;
                            if (newRateCount === 1) {
                                return this.keep();
                            }
                            else {
                                return this.filter();
                            }
                        }
                        else {
                            return this.keep();
                        }
                    });
                    window.currentTimeout = setTimeout(() => this.setState({ renderedRates: willRenderRates, timeout: timer }), timer);                   
                    return this.breakLoop();
                }
            });

            if (!updated && currentOnScreenRates.length > newRates.length) {
                // all of first ones are in order already, however:
                // newRates are fewer than currentOnScreenRates, therefore:
                // just need to remove old rates.
                updated = true;
                willRenderRates = currentOnScreenRates.slice(0, newRates.length);
                window.currentTimeout = setTimeout(() => this.setState({ renderedRates: willRenderRates, timeout: timer }), timer);
            }

            output = updated ? willRenderRates : newRates;
        }
        return output;
    }
```

This seems to fix even aggressive hammering of removals/additions.

cc @ConneXNL @Arinteck @vsaarinen @ohjames @migreva @RyanCCollins @benjiwheeler @joshwcomeau

**Comment by joshwcomeau** [comment] 2016-12-13 11:47
Thanks for sharing, @finetype! Sorry to hear that throttling was so much trouble :(

**Comment by finetype** [comment] 2016-12-13 16:23
@joshwcomeau
Still a great library. It's an incredibly hard problem to solve. We'll get it fixed sooner or later. Would you be amenable to a version with a temporary optional 'hotfix' parameter in the meantime that implements this internally, or would I be wasting my time/would you rather just wait until it's properly fixed?

**Comment by ohjames** [comment] 2016-12-26 13:47
At kchomp.co you can see flip move sometimes fails to remove items, even with the latest version. This leads to the list being rendered out of order sometimes also. Looks related to the discussion here.

**Comment by finetype** [comment] 2017-02-09 21:22
I later wrote a nicer callback version, and pushing it to production was my last activity before leaving the company. Sadly, I didn't get around to saving a copy of that code. :(
