### ISSUE TITLE
Problem with leave animation and scroll

### ISSUE THREAD

**Issue by SDSLeon** [joshwcomeau/react-flip-move#56] opened 2016-06-15 11:36 UTC
Animation start break if you have scroll, you scroll to the end and start delete items from the list;
                        staggerDurationBy={150}
                        duration={350}
                        enterAnimation='fade'
                        leaveAnimation='fade'

**Comment by joshwcomeau** [comment] 2016-06-17 10:30
Not sure I understand... Can you provide some more info? Do you mean a scroll event, or just window scrolling? What happens specifically if you scroll while the animation is in progress? An example .gif would be great :)

**Comment by SDSLeon** [comment] 2016-06-17 11:32
[flip-move-1.mp4.zip](https://github.com/joshwcomeau/react-flip-move/files/320338/flip-move-1.mp4.zip)
[flip-move-2.mp4.zip](https://github.com/joshwcomeau/react-flip-move/files/320343/flip-move-2.mp4.zip)

**Comment by joshwcomeau** [comment] 2016-06-17 11:43
Oh I see. Thanks for the videos!

Yeah, the problem is that the container's size instantly changes, it doesn't "transition". This has been discussed in #40.

Maybe I should work out an in-house solution since it seems to be a pretty common request. In the meantime, though, you can solve this problem by calculating and animating the parent container size yourself :) hopefully that issue (#40) can point you in the right direction.

**Comment by joshwcomeau** [comment] 2016-07-08 14:12
Going to close this, because I believe it's currently outside the scope of FlipMove, and something that should be handled in userland.

**Closed by joshwcomeau** 2016-07-08 14:12 UTC
Labels: bug
