### ISSUE TITLE
Customize re-order animation

### ISSUE THREAD

**Issue by deibeljc** [joshwcomeau/react-flip-move#127] opened 2017-02-14 22:24 UTC
I have a use case where I want the re-order animation to behave like such:

when an element wants to move up the list it will essentially animate out (translate up and make opacity 0). When it "reaches" that location it will translate up into the spot and make opacity 1.

Right now the only way I could think to do this was to chain state changes where an item leaves triggering the leaving animation and then enter.

**Comment by joshwcomeau** [comment] 2017-02-14 22:59
Hm, yeah, that's a tricky one. To be honest, Flip Move wasn't really built to be a flexible, abstract tool; it exists to fluidly move stuff around on a screen when props change.

Thankfully, Flip Move provides escape hatches that _should_ make stuff like this possible. Here's what I've come up with.

### In CSS
I think the way to do this would be to use the `onStart` hook. They're given the direct DOM elements as arguments, so you could apply a class that has the animation you need.

```css
@keyframes stealthFlipMove {
  0% { opacity: 1 }
  25% { opacity: 0 }
  75% { opacity: 0 }
  100% { opacity: 1 }
}

.stealth {
  animation: stealthFlipMove 600ms; /* make this equal to your `duration` */
}
```

```js
<FlipMove
  onStart={(elem, node) => {
    elem.classList.add('stealth');
  }}
```

This isn't a great solution: Unless you're using a CSS-in-JS solution like Aphrodite, you have to hardcode your animation duration in the CSS, which is brittle. Additionally, if your shuffle is interrupted, the animation won't restart, unless you unset and reset the class within that `onStart` callback.


### In JS
An alternative could be to handle the animations from within JS. The [Web Animations API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Animations_API) has tools to handle interrupts, and could be a great way to accomplish this effect. The downside is it has terrible browser support, so you'd need a polyfill.


Let me know if these solutions are workable. Curious to see the final product if you get it working!

**Comment by deibeljc** [comment] 2017-02-14 23:12
@joshwcomeau ah okay cool. I will see if adding the css on the lifecycle works for me, otherwise I will play around with being able to declare via props how the movement animation behaves.

I also have been attempting to beef up the customization you can do to create a more rich and complex animation. I'll open up a separate issue regarding those to detail my requirements and changes and what-not!

**Comment by joshwcomeau** [comment] 2017-02-15 02:45
Yeah, so if you're already taking the time to fork Flip Move, it's probably easier to just add support for it that way. I'm not entirely sure what the best way would be, but you can probably add a `shuffleAnimation` prop that behaves like `enterAnimation`.

Going to close it as it's not a bug nor a feature I plan on implementing, but please do follow up and let me know what you wound up doing.

(also, it sounds like you're building something pretty neat. If it winds up being publicly available, I'd love to see it!)

**Closed by joshwcomeau** 2017-02-15 02:45 UTC
