### ISSUE TITLE
EnterAnimation/LeaveAnimation is always default

### ISSUE THREAD

**Issue by yofret** [joshwcomeau/react-flip-move#107] opened 2016-11-23 21:46 UTC
Hi I'm trying to change the default animation to a fade effect, but it always show the elevator effect even if I set enterAnimation/leaveAnimation props to **'fade'**

This is my code

```
    <FlipMove typeName='ul'
        className='items-list'
        enterAnimation='fade'
        leaveAnimation='fade'
        easing='cubic-bezier(0.23,1,0.32,1)'>
        {this._renderList()}
    </FlipMove>

// Render Function

    _renderList(){
        return this.state.items.map(function(item, index){
            return <Item key={item.key} index={index} />
        }.bind(this))
    },
```

**Comment by joshwcomeau** [comment] 2016-11-24 12:46
Hi @yofret,

Hm, I'm unable to reproduce this issue - fade animations work for me.

I just created a fiddle with basic FlipMove configuration: https://jsbin.com/cusaqayuyi. 

If you can modify this fiddle to recreate the issue, I'll be happy to take a look and see what's up :)

**Comment by yofret** [comment] 2016-11-24 15:32
Hi @joshwcomeau 

I've made some modifications to resemble my current scenario, In any given time I might populate and repopulate the current <FlipMove> Instance, that causes some strange behaviour

https://jsbin.com/kaqato/edit?html,css,js,output

**Comment by rhys-vdw** [comment] 2016-11-24 23:24
So i'm having this problem with your gist. It happens whether I use the "fade" animation or not.

![shuffle-fail](https://cloud.githubusercontent.com/assets/822105/20610973/2ccdf68c-b2f6-11e6-8ce9-f37e7ebe858d.gif)

It's because `boundingBox` is undefined [here](https://github.com/joshwcomeau/react-flip-move/blob/8f6df3235800700b7095a4c4cc00230f4d652fae/src/dom-manipulation.js#L141).

**Comment by rhys-vdw** [comment] 2016-11-24 23:37
In fact I get the same error with your original Gist, @joshwcomeau. Try [this copy of your fiddle](https://output.jsbin.com/munocu) with more items. Hit "remove 1 item" quickly to empty the list. Then press restore and try again.

(Happens in Chrome and Firefox

Can't see the animation error reported by @yofret.

**Comment by yofret** [comment] 2016-11-25 00:02
I was able to see the issue the first time i swap from one array to another, then no animation at all,  just like the gif you posted

**Comment by joshwcomeau** [comment] 2016-11-25 12:13
Huh, strange. Will spend some time this weekend seeing if I can sort this out.

**Comment by joshwcomeau** [comment] 2016-12-03 14:48
I believe this is a duplicate of #106, so I'm going to close this issue. Discussion can continue in that thread :)

**Closed by joshwcomeau** 2016-12-03 14:48 UTC
