### ISSUE TITLE
Rendering component to null causes error

### ISSUE THREAD

**Issue by ajcronk** [joshwcomeau/react-flip-move#102] opened 2016-11-19 02:29 UTC
I have a list of components (called Factor), and if I don't want to show the item I render the component null.  This inserts a react-empty which seems to be causing the getBoundingClientRect error in the screenshot below.

If I show all of the components (so all react-empty are gone), everything works great.

Is there a better way to conditionally display the items?  Or perhaps another workaround?  I apologize, I'm not familiar enough with this library yet to recommend a patch.

![screen shot 2016-11-18 at 8 20 55 pm](https://cloud.githubusercontent.com/assets/60509/20452333/da1fae90-adcc-11e6-9f28-b79e3d67dfb5.png)

**Comment by rhys-vdw** [comment] 2016-11-19 07:20
Hi @ajcronk. Could you check if PR #100 corrects this issue? The comment [here](https://github.com/yp/react-flip-move/blob/997bc18bfac76322fb5218945dd9ae7eedf5b43d/src/prop-converter.js#L38-L39) suggests that this may be related.

This PR has not yet been merged but not yet released, so you can check by pointing you package.json `dependencies` entry to our `master` branch:

```js
"dependencies": {
  // ...
  "react-flip-move": "joshwcomeau/react-flip-move"
  // ...
}
```

**Comment by rhys-vdw** [comment] 2016-11-19 07:26
Actually the fix was included in version 2.6.10, so please check that you've got the latest release.

**Comment by joshwcomeau** [comment] 2016-11-19 13:32
Hey @ajcronk,

Rhys took the words out of my mouth :) Please let me know if the issue persists in the latest version. If so I'll take a closer look, but I believe this issue was already fixed.

**Comment by ajcronk** [comment] 2016-11-19 19:55
Thanks for the quick responses.  I saw the other tickets, and had checked my package versions.  This is what I pulled off of an npm install.

react 15.3.2
react-flip-move 2.7.0-beta1

Seems that the 2.7.0-beta should include the fix?  Should I try different package versions of react or react-flip-move?

**Comment by ajcronk** [comment] 2016-11-19 20:20
Tried to install 2.6.8 from source from this page: https://github.com/joshwcomeau/react-flip-move/releases

Looks like the 2.6.8 tar/zip shows "version":"2.6.7" in package.json?  

Probably unrelated, but found when trying out different versions.

**Comment by yp** [comment] 2016-11-19 20:32
I had the same (or a very similar) issue, but version 2.6.10 fixed the problem.
Can you provide a minimal example that reproduces the bug?

**Comment by ajcronk** [comment] 2016-11-19 20:53
@yp will put together an example in a bit.

I'm confused though - I see the changes here were merged:
https://github.com/joshwcomeau/react-flip-move/pull/100/files

But they aren't in master? 
https://github.com/joshwcomeau/react-flip-move/blob/master/src/prop-converter.js

I downloaded the 2.6.10 release from npm and saw similar code to master without the fix?

Am I reading this wrong?

**Comment by rhys-vdw** [comment] 2016-11-19 23:05
@ajcronk it's just that the exact implementation was changed [in a subsequent commit](https://github.com/joshwcomeau/react-flip-move/commit/a0b71b464d1cee09aa7d36e2a2b30b1fbdd1586a#diff-ecdb6cdeb1de0c9f5925708a2be17e73). The use of `React.Children.toArray` is the important part, and is [still present in current master head commit](https://github.com/joshwcomeau/react-flip-move/blob/a0b71b464d1cee09aa7d36e2a2b30b1fbdd1586a/src/prop-converter.js#L39).

**Comment by rhys-vdw** [comment] 2016-11-19 23:15
> This is what I pulled off of an npm install.
>
> react 15.3.2
> react-flip-move 2.7.0-beta1

@joshwcomeau When publishing a beta version, you should publish using command `npm publish --tag beta`. npm will not infer alpha/beta/rc status from the version string, and will default to `latest`, which is the version installed by `npm install` by default. See [npm documentation](https://docs.npmjs.com/getting-started/using-tags).

**Comment by rhys-vdw** [comment] 2016-11-19 23:22
> Seems that the 2.7.0-beta should include the fix?

@ajcronk, it does seems that it [should include the fix](https://github.com/joshwcomeau/react-flip-move/commits/da50af9faec783a11cd3db3bd1c2c240223bce5c).

**Comment by ajcronk** [comment] 2016-11-20 03:37
I found a workaround to my issue that doesn't involve code changes to this library.  I spent a couple hours deep in debugger land to learn more about what was going on.  I now know enough to work around my error :)

I'll describe what I was doing, and how I produced the error, in case anyone is interested.

I was mapping over 5 item components that would output an <li> if they had a prop called "visible" set to true.  If visible was false, the component would render null (hence the react-empty above in the screenshot).  The state of the item components is lifted up and managed in a single array in a list component.

On initial page load, only the first item (Item1) component had visible set true.  At this point, there were still 5 children, but only one of them was in the DOM.  The rest were react-empty.

In the UI, you click a button which sets the second component (Item2) visible to true in the lifted up list component array, and then setState is called to update the array.  Here is where the error is introduced.

getBoundingClientRect is eventually called on Item2, which doesn't exist in the DOM yet, but does have visible set true, so would render an <li> now.  However, the node is null when passed into getBoundingClientRect.

My fix is to get rid of the react-emptys altogether by changing my initial function where I map over the 5 item components to only return the component if the item is visible.  If the item is not visible, then don't even call the item component.

If you're still reading (thank you!), is there a better way to toggle visibility like this?

**Comment by rhys-vdw** [comment] 2016-11-20 03:52
Hey @ajcronk. Is this what you mean?

### before
_Raises exception_
```jsx
class Item extends Component
  render({ visible, content }) {
    return visible ? <li>{content}<li> : null
  }
}

function List({ items }) {
  return (
    <FlipMove>
      {items.map(item => <Item {...item} />)}
    </FlipMove>
  )
}
```

### after
_Working fine_
```jsx
class Item extends Component
  render({ content }) {
    return <li>{content}<li>
  }
}

function List({ items }) {
  return (
    <FlipMove>
      {items.filter(item => item.visible).map(item => <Item content={item.content} />)}
    </FlipMove>
  )
}
```

**Comment by ajcronk** [comment] 2016-11-20 03:58
@rhys-vdw Yes, that is correct.  In the Before case, all Items are children, and in the After case they are progressively added as children (I think).

**Comment by rhys-vdw** [comment] 2016-11-20 04:07
@ajcronk Well, there is nothing interesting about the latter (working) case case from our point of view. Both patterns should be supported. It would be a big help to get a minimal reproduction with latest version of react-flip-move if you're able/willing to put in the effort.

**Comment by ajcronk** [comment] 2016-11-20 04:09
@rhys-vdw sure, I'd be glad to put that together.  Prob in the next couple days.

**Comment by ajcronk** [comment] 2016-11-20 04:45
@rhys-vdw gave it a quick go.

Does this make sense?

https://gist.github.com/ajcronk/c7adb6e501d17986ef98f19400da0f86

Expected behavior is click the button and Item2 appears.  Should work as is.

To see failing behavior, comment out line 29, and uncomment line 32.

You'll see the only difference between the two lines is pre-filtering out the visible=false items.

**Comment by joshwcomeau** [comment] 2016-11-20 11:35
@ajcronk thanks for providing a reproduction!

@rhys-vdw let me know if you'd like me to tackle this one, otherwise I'll leave it in your capable hands :)

RE: published version: huh, surprised I forgot to use a tag. Could've sworn I did, but you're right, it appears not. I believe v2.7.0 is ready to go anyway, so I'll publish a proper release this morning.

**Comment by rhys-vdw** [comment] 2016-11-20 22:14
@joshwcomeau I can't guarantee I will deal with this in a timely fashion, so feel free to complete it. Just post in this thread if you're looking into it. Otherwise I'll see if I get a chance one evening this week.

**Comment by joshwcomeau** [comment] 2016-11-23 12:24
Ah-ha - Yeah, after looking into it, I understand why it's broken. 

We check for null values when processing children, and in this case, Flip Move is handed valid React elements; the issue is that _those elements_ render null. Essentially:

```js
<FlipMove>
  <CustomComponent />
</FlipMove>

class CustomComponent extends Component {
  render() {
    return null;
  }
}
```

Should be an easy fix.

**Closed** 2016-11-23 12:39 UTC
Labels: bug
