### ISSUE TITLE
Flow type complains about several issues with react-flip-move

### ISSUE THREAD

**Issue by kentcdodds** [joshwcomeau/react-flip-move#157] opened 2017-05-15 18:17 UTC
Like [this one](https://github.com/joshwcomeau/react-flip-move/blob/master/src/enter-leave-presets.js#L61)

```
node_modules/react-flip-move/src/enter-leave-presets.js:61
 61: // $FlowFixMe
     ^^^^^^^^^^^^^ Error suppressing comment. Unused suppression
```

I'm pretty sure you should be able to remove that. Actually, there are quite a few flow-related issues. I think it may be best to remove `src` from the `package.json`. But I could be wrong. I've not done much with flow in OSS yet...

Here are all the errors I get:

<details>
<summary>all of the errors</summary>

```
node_modules/react-flip-move/lib/FlipMove.js.flow:57
 57:   state = {
       ^ Experimental class instance field usage. Class instance fields are an active early stage feature proposal that may change. You may opt-in to using them anyway in Flow by putting `esproposal.class_instance_fields=enable` into the [options] section of your .flowconfig.

node_modules/react-flip-move/lib/FlipMove.js.flow:69
 69:   childrenData: {
       ^ Experimental class instance field usage. Class instance fields are an active early stage feature proposal that may change. You may opt-in to using them anyway in Flow by putting `esproposal.class_instance_fields=enable` into the [options] section of your .flowconfig.

node_modules/react-flip-move/lib/FlipMove.js.flow:82
 82:   parentData: NodeData = {
       ^ Experimental class instance field usage. Class instance fields are an active early stage feature proposal that may change. You may opt-in to using them anyway in Flow by putting `esproposal.class_instance_fields=enable` into the [options] section of your .flowconfig.

node_modules/react-flip-move/lib/FlipMove.js.flow:91
 91:   heightPlaceholderData: NodeData = {
       ^ Experimental class instance field usage. Class instance fields are an active early stage feature proposal that may change. You may opt-in to using them anyway in Flow by putting `esproposal.class_instance_fields=enable` into the [options] section of your .flowconfig.

node_modules/react-flip-move/lib/FlipMove.js.flow:101
101:   remainingAnimations = 0;
       ^^^^^^^^^^^^^^^^^^^^^^^^ Experimental class instance field usage. Class instance fields are an active early stage feature proposal that may change. You may opt-in to using them anyway in Flow by putting `esproposal.class_instance_fields=enable` into the [options] section of your .flowconfig.

node_modules/react-flip-move/lib/FlipMove.js.flow:102
102:   childrenToAnimate: Array<string> = [];
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Experimental class instance field usage. Class instance fields are an active early stage feature proposal that may change. You may opt-in to using them anyway in Flow by putting `esproposal.class_instance_fields=enable` into the [options] section of your .flowconfig.

node_modules/react-flip-move/lib/FlipMove.js.flow:164
164:   runAnimation = () => {
       ^ Experimental class instance field usage. Class instance fields are an active early stage feature proposal that may change. You may opt-in to using them anyway in Flow by putting `esproposal.class_instance_fields=enable` into the [options] section of your .flowconfig.

node_modules/react-flip-move/lib/FlipMove.js.flow:180
180:   doesChildNeedToBeAnimated = (child: ChildData) => {
       ^ Experimental class instance field usage. Class instance fields are an active early stage feature proposal that may change. You may opt-in to using them anyway in Flow by putting `esproposal.class_instance_fields=enable` into the [options] section of your .flowconfig.

node_modules/react-flip-move/lib/FlipMove.js.flow:357
357:     requestAnimationFrame(() => {
         ^^^^^^^^^^^^^^^^^^^^^ identifier `requestAnimationFrame`. Could not resolve name

node_modules/react-flip-move/lib/dom-manipulation.js.flow:152
152:     [string]: number,
                ^ Unexpected token ]

node_modules/react-flip-move/lib/enter-leave-presets.js.flow:59
 59: // $FlowFixMe
     ^^^^^^^^^^^^^ Error suppressing comment. Unused suppression

node_modules/react-flip-move/lib/enter-leave-presets.js.flow:61
 61: // $FlowFixMe
     ^^^^^^^^^^^^^ Error suppressing comment. Unused suppression

node_modules/react-flip-move/lib/enter-leave-presets.js.flow:63
 63: // $FlowFixMe
     ^^^^^^^^^^^^^ Error suppressing comment. Unused suppression

node_modules/react-flip-move/lib/enter-leave-presets.js.flow:65
 65: // $FlowFixMe
     ^^^^^^^^^^^^^ Error suppressing comment. Unused suppression

node_modules/react-flip-move/lib/helpers.js.flow:40
 40: function memoizeString<T>(fn: (string) => T): (string) => T {
                                            ^^ Unexpected token =>

node_modules/react-flip-move/lib/prop-converter.js.flow:63
 63:     static defaultProps = {
         ^ Experimental class static field usage. Class static fields are an active early stage feature proposal that may change. You may opt-in to using them anyway in Flow by putting `esproposal.class_static_fields=enable` into the [options] section of your .flowconfig.

node_modules/react-flip-move/lib/typings.js.flow:5
  5:   [string]: string,
              ^ Unexpected token ]

node_modules/react-flip-move/src/FlipMove.js:57
 57:   state = {
       ^ Experimental class instance field usage. Class instance fields are an active early stage feature proposal that may change. You may opt-in to using them anyway in Flow by putting `esproposal.class_instance_fields=enable` into the [options] section of your .flowconfig.

node_modules/react-flip-move/src/FlipMove.js:69
 69:   childrenData: {
       ^ Experimental class instance field usage. Class instance fields are an active early stage feature proposal that may change. You may opt-in to using them anyway in Flow by putting `esproposal.class_instance_fields=enable` into the [options] section of your .flowconfig.

node_modules/react-flip-move/src/FlipMove.js:82
 82:   parentData: NodeData = {
       ^ Experimental class instance field usage. Class instance fields are an active early stage feature proposal that may change. You may opt-in to using them anyway in Flow by putting `esproposal.class_instance_fields=enable` into the [options] section of your .flowconfig.

node_modules/react-flip-move/src/FlipMove.js:91
 91:   heightPlaceholderData: NodeData = {
       ^ Experimental class instance field usage. Class instance fields are an active early stage feature proposal that may change. You may opt-in to using them anyway in Flow by putting `esproposal.class_instance_fields=enable` into the [options] section of your .flowconfig.

node_modules/react-flip-move/src/FlipMove.js:101
101:   remainingAnimations = 0;
       ^^^^^^^^^^^^^^^^^^^^^^^^ Experimental class instance field usage. Class instance fields are an active early stage feature proposal that may change. You may opt-in to using them anyway in Flow by putting `esproposal.class_instance_fields=enable` into the [options] section of your .flowconfig.

node_modules/react-flip-move/src/FlipMove.js:102
102:   childrenToAnimate: Array<string> = [];
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Experimental class instance field usage. Class instance fields are an active early stage feature proposal that may change. You may opt-in to using them anyway in Flow by putting `esproposal.class_instance_fields=enable` into the [options] section of your .flowconfig.

node_modules/react-flip-move/src/FlipMove.js:164
164:   runAnimation = () => {
       ^ Experimental class instance field usage. Class instance fields are an active early stage feature proposal that may change. You may opt-in to using them anyway in Flow by putting `esproposal.class_instance_fields=enable` into the [options] section of your .flowconfig.

node_modules/react-flip-move/src/FlipMove.js:180
180:   doesChildNeedToBeAnimated = (child: ChildData) => {
       ^ Experimental class instance field usage. Class instance fields are an active early stage feature proposal that may change. You may opt-in to using them anyway in Flow by putting `esproposal.class_instance_fields=enable` into the [options] section of your .flowconfig.

node_modules/react-flip-move/src/FlipMove.js:357
357:     requestAnimationFrame(() => {
         ^^^^^^^^^^^^^^^^^^^^^ identifier `requestAnimationFrame`. Could not resolve name

node_modules/react-flip-move/src/dom-manipulation.js:152
152:     [string]: number,
                ^ Unexpected token ]

node_modules/react-flip-move/src/enter-leave-presets.js:59
 59: // $FlowFixMe
     ^^^^^^^^^^^^^ Error suppressing comment. Unused suppression

node_modules/react-flip-move/src/enter-leave-presets.js:61
 61: // $FlowFixMe
     ^^^^^^^^^^^^^ Error suppressing comment. Unused suppression

node_modules/react-flip-move/src/enter-leave-presets.js:63
 63: // $FlowFixMe
     ^^^^^^^^^^^^^ Error suppressing comment. Unused suppression

node_modules/react-flip-move/src/enter-leave-presets.js:65
 65: // $FlowFixMe
     ^^^^^^^^^^^^^ Error suppressing comment. Unused suppression

node_modules/react-flip-move/src/helpers.js:40
 40: function memoizeString<T>(fn: (string) => T): (string) => T {
                                            ^^ Unexpected token =>

node_modules/react-flip-move/src/prop-converter.js:63
 63:     static defaultProps = {
         ^ Experimental class static field usage. Class static fields are an active early stage feature proposal that may change. You may opt-in to using them anyway in Flow by putting `esproposal.class_static_fields=enable` into the [options] section of your .flowconfig.

node_modules/react-flip-move/src/typings.js:5
  5:   [string]: string,
              ^ Unexpected token ]


Found 34 errors
```

</details>

**Comment by kentcdodds** [comment] 2017-05-15 18:18
For anyone else running into this, I get around this with this in my `.flowconfig`:

```
[ignore]
.*/node_modules/react-flip-move/*
```

**Comment by joshwcomeau** [comment] 2017-05-15 18:28
Hi @kentcdodds,

Thanks for pointing this out. We only recently type-annotated our source, and it hadn't occurred to me that Flow would run within node_modules in others' projects.

But you're right, it probably makes sense to drop `/src` from the distributed NPM package. I can't imagine this being problematic, but I'll still start with a beta release and try it on a side project myself, to be sure.

(BTW - I really enjoyed Javascript Air :) was sad to see it go, but totally understand the desire to free up time for your projects)

**Comment by Hypnosphi** [comment] 2017-05-15 19:09
>it probably makes sense to drop /src

Those come not only from `src` but also from `lib/*.flow.js`, which is quite useful to keep, because it gives type info to flow users. I think we should fix the warnings and update the flowconfig instead

**Comment by Hypnosphi** [comment] 2017-05-15 19:19
@kentcdodds I need a way to reproduce the errors. Which version of Flow do you use and what's your `.flowconfig`?

**Comment by joshwcomeau** [comment] 2017-05-15 19:30
> Those come not only from src but also from lib/*.flow.js, which is quite useful to keep, because it gives type info to flow users. I think we should fix the warnings and update the flowconfig instead

Ahh, right. Looking at the errors shared, some are indeed coming from `/lib`.

I'm obviously not terribly experienced with Flow, but is this something we could use [Flow Typed](https://github.com/flowtype/flow-typed) for? To share the type definitions separately from the library itself, so that non-flow users don't have anything unneeded shared?

**Comment by Hypnosphi** [comment] 2017-05-15 19:34
Flow typed is for libraries not themsleves written with flow. Sharing the untranspiled sources is the recommended way to share flow typings

**Comment by kentcdodds** [comment] 2017-05-15 19:37
Hmmm.... Interesting. Is that recommendation documented anywhere? I have an issue with distributing untranspiled sources.

**Comment by Hypnosphi** [comment] 2017-05-15 19:53
> Is that recommendation documented anywhere?

Unfortunately, [not really](https://github.com/facebook/flow/issues/1996#issuecomment-230919868)

**Comment by kentcdodds** [comment] 2017-05-15 20:06
Sorry, just saw your request for the `.flowconfig`. Here it is:

```
[options]
suppress_type=$FlowIssue
suppress_type=$FlowFixMe
suppress_comment= \\(.\\|\n\\)*\\$FlowFixMe

# webpack loaders
module.name_mapper='.*\.svg$' -> '<PROJECT_ROOT>/lib/flow-svg-loader.js'

# handle the modules resolution to public/js
# this one only handles 'lib/', 'transfer/' or 'calculator/' paths.
# Would need adjustment to handle more paths if that's needed.
module.name_mapper='^\(lib\|transfer\|calculator\|react-components\)\/\(.*\)$' -> '<PROJECT_ROOT>/public/js/\1/\2'

[ignore]
.*/node_modules/.*[^e]\.json$
.*/node_modules/.*\(lib\|test\).*\.json$
.*/node_modules/flux/*
.*/node_modules/fbemitter/*
.*/node_modules/.*fbjs/*
.*/node_modules/jest-*/*
# just added this 👇
.*/node_modules/react-flip-move/*
```

**Comment by Hypnosphi** [comment] 2017-05-15 20:41
Looks like you're using some pre-0.33.0 version of Flow which had [`esproposal.class_instance_fields`](https://flow.org/en/docs/config/options/#toc-esproposal-class-instance-fields-enable-ignore-warn) set to `warn` by default (now it's `enable`). We could override that in our `.flowconfog`, but unfortunately Flow would [ignore](https://github.com/facebook/flow/issues/238) that. So maybe we need to create to libdef. There's an experimental command `flow gen-flow-files` for that. Let's see if it works for us.

**Comment by Hypnosphi** [comment] 2017-05-15 20:55
That's what's generated:  https://gist.github.com/Hypnosphi/e60e71431edabe305028c49b3de450f3
I don't really like it =(

**Comment by Hypnosphi** [comment] 2017-05-16 00:31
https://github.com/flowtype/flow-typed/pull/844

**Comment by joshwcomeau** [comment] 2017-05-17 11:24
Thanks for addressing this @Hypnosphi! I'm happy with the solution that was landed on :D

**Closed** 2017-05-24 23:15 UTC
Labels: bug
